// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>
#include <arduino_secrets.h>
#include <ESP8266WiFi.h>
#include <ArduinoOTA.h>

const char DEVICE_LOGIN_NAME[]  = "542272da-d1a0-42bb-ba38-634252f4438d";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onOnOffChange();
void onFanChange();
void onModeChange();
void onTempChange();
void onIsOnChange();

CloudSwitch isOn;
int fan;
int mode;
int temp;
bool onOff;

void wifi_connect() {
    WiFi.persistent(false);
    WiFi.mode(WIFI_STA);
    WiFi.setAutoReconnect(true);
    WiFi.begin(SSID, PASS);
    Serial.println("WiFi connecting...");
    while (!WiFi.isConnected()) {
        delay(100);
        Serial.print(".");
    }
    Serial.print("\n");
    Serial.printf("WiFi connected, IP: %s\n", WiFi.localIP().toString().c_str());

}

void initProperties(){

    ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
    ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
    ArduinoCloud.addProperty(onOff, READWRITE, ON_CHANGE, onOnOffChange);
    ArduinoCloud.addProperty(fan, READWRITE, ON_CHANGE, onFanChange);
    ArduinoCloud.addProperty(mode, READWRITE, ON_CHANGE, onModeChange);
    ArduinoCloud.addProperty(temp, READWRITE, ON_CHANGE, onTempChange);
    ArduinoCloud.addProperty(isOn, READWRITE, ON_CHANGE, onIsOnChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
